### ISSUE TITLE
Fix Javadoc errors to remove JDK8 build warnings and regenerate site

### ISSUE THREAD

**Issue by ottlinger** [ottlinger/fotorenamer#16]
## Tasks
At the moment javadoc:javadoc is not working smoothly:
* [x] fix javadoc warnings
* [x] regenerate site and link to it
* [ ] fix Codacy issues

## Warnings
```
[WARNING] Javadoc Warnings
[WARNING] fotorenamer/src/test/java/de/aikiit/bildbearbeiter/image/CreationDateFromExifImageRenamerTest.java:31: warning: no @throws for java.lang.Exception
[WARNING] public final void checkNPECorrectnessInConstructor() throws Exception {
[WARNING] ^
[WARNING] fotorenamer/src/test/java/de/aikiit/bildbearbeiter/image/CreationDateFromExifImageRenamerTest.java:51: warning: no @throws for java.lang.Exception
[WARNING] public final void renameTestImageAndDeleteFileAfterwards() throws
[WARNING] ^
[WARNING] fotorenamer/src/test/java/de/aikiit/bildbearbeiter/image/MetaDataExtractorTest.java:23: warning: no description for @throws
[WARNING] * @throws Exception
[WARNING] ^
[WARNING] fotorenamer/src/test/java/de/aikiit/bildbearbeiter/image/MetaDataExtractorTest.java:37: warning: no @throws for java.lang.Exception
[WARNING] public void checkAssertionErrors() throws Exception {
[WARNING] ^
[WARNING] fotorenamer/src/test/java/de/aikiit/bildbearbeiter/util/ComponentGaugeUtilTest.java:25: warning: no @throws for java.lang.Exception
[WARNING] public final void createIconFromStringPath() throws Exception {
[WARNING] ^
[WARNING] fotorenamer/src/test/java/de/aikiit/bildbearbeiter/util/ComponentGaugeUtilTest.java:45: warning: no @throws for java.lang.Exception
[WARNING] public void gaugeSwingComponent() throws Exception {
```
